export const GET_ERRORS = 'GET_ERRORS';
export const GET_REPOS_SUCCESS = 'GET_REPOS_SUCCESS';
export const GET_AUTHOR_SUCCESS = 'GET_AUTHOR_SUCCESS';
export const GET_HOME_SUCCESS = 'GET_HOME_SUCCESS';
